language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: WX0K/wzf8TFs19jP+T+Yuzjr94aTQNpCrrCH0jr9MKsbhKverRACKrQnQTiTWv4yij2EIwEcch7mye0ijCMiqyNua2yqZxeRlS6uwY7EXS7JVMyiDuliB6ycZ2D7pUnvp0WUgpFvpZ54jq9M2EnV3Q4qJNzfMu1OEzbkwooBw+UoOee8u5zDL9jjt2lvxq57uTKK1Vk4nQFr33uVwHwW4eoUrDmNXRQzhU4s0A7C7u/PjD8Ujo2ayrYM6gUM3SyK01CYQWAaIxbGJE2ePccA8CpdtFcocx2ImFlERANAnon/6/U+kaH4+ZUXEPk2TjfGJHNLw3Bg6uS3sCxebMKdl5zB9b/lApelIC1prKuD+SoPMz5TgwwLJVqFXTlvGyavuqFR+++xndUiLbiUWGUkk4w+EQnyE6k/iyU4/WT5EXQCAMKMb6dFq6L0uzF/C0kCEvggyoYm/lfBo8BJjZhvxeWoEfoqRZXnzJjg9c0+aob1nfZyPmL+2BDLOseu2kLQyMaNgHNZn2g9VgLrdfBVVcATbfJx/aaw8tpTitxFUStT16l2URfLbTotI4M5/xBPl4EfmEmXJJ1CSgnHpXGE7Ty3o3pcosQtJu3I9+lNNB41IYYgXx8oq27e4NaaDmduMyBjArRdIpUdHEwQtfp6SZecx864hzvPZP9Y4inuB3E=
